test -e /opt/homebrew/bin/brew &&
    export PATH=/opt/homebrew/bin:~/Applications/Tools/bin:$PATH \
        HOMEBREW_BUNDLE_FILE=$HOME/.Brewfile &&
    eval "$(/opt/homebrew/bin/brew shellenv)" &&
    test -t 0 &&
    source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh &&
    source "$HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh" 2> /dev/null

export HISTFILE=~/.histfile HISTSIZE=5000 SAVEHIST=5000
setopt share_history hist_ignore_all_dups hist_ignore_space
autoload -Uz compinit promptinit
compinit && promptinit
prompt walters
source <(fzf --zsh)

bindkey -v
alias ls="ls --color"
